import { ThemeLayoutConfig } from '../types';

const compact: ThemeLayoutConfig = {
  height: {
    lg: '40px',
    md: '32px',
    sm: '24px',
    xs: '16px',
    xss: '8px',
  },
  width: {
    lg: '40px',
    md: '32px',
    sm: '24px',
    xs: '16px',
    xss: '8px',
  },
  margin: {
    lg: '24px',
    md: '16px',
    sm: '8px',
    xs: '4px',
    xss: '2px',
  },
  padding: {
    lg: '24px',
    md: '16px',
    sm: '8px',
    xs: '4px',
    xss: '2px',
  },
  alert: {
    fontSize: '12px',
    iconSize: '16px',
    borderWidth: '1px',
    borderLeftWidth: '3px',
  },
  autoComplete: {
    fontSize: '12px',
    iconSize: '14px',
    wrapperHeight: '24px',
    wrapperLineHeight: '24px',
    inputHeight: '22px',
    inputLineHeight: '22px',
    itemHeight: '18px',
    itemLineHeight: '18px',
  },
  badge: {
    fontSize: '10px',
    height: '20px',
    lineHeight: '20px',
    width: '20px',
  },
  button: {
    fontSize: '12px',
    iconSize: '12px',
    iconButtonWidth: '24px',
    buttonHeight: '24px',
    buttonPadding: '0px 8px',
  },
  card: {
    descriptionSize: '12px',
    iconSize: '32px',
    padding: '8px',
    titleSize: '14px',
  },
  checkbox: {
    fontSize: '12px',
    wrapperHeight: '24px',
    wrapperLineHeight: '24px',
  },
  collapse: {
    fontSize: '12px',
    iconSize: '16px',
    collapseHeight: '32px',
  },
  colorPicker: {
    pickerHeight: '16px',
    pickerWidth: '16px',
    pickerMargin: '4px',
  },
  dataList: {
    fontSize: '12px',
    iconSize: '18px',
    height: '24px',
    lineHeight: '24px',
    width: '24px',
    padding: '8px',
  },
  dataTable: {
    fontSize: '12px',
    iconSize: '16px',
    height: '32px',
    lineHeight: '32px',
    padding: '8px',
    toolbarHeight: '32px',
  },
  divider: {
    fontSize: '12px',
    height: '24px',
  },
  dropDown: {
    fontSize: '12px',
    iconSize: '12px',
    itemHeight: '24px',
    itemLineHeight: '24px',
  },
  empty: {
    fontSize: '14px',
    iconSize: '32px',
    margin: '8px',
  },
  field: {
    height: '24px',
  },
  filter: {
    fontSize: '12px',
  },
  form: {
    fontSize: '12px',
  },
  gridView: {
    fontSize: '12px',
    padding: '8px',
  },
  header: {
    fontSize: '16px',
    iconSize: '16px',
  },
  icon: {
    iconSize: '18px',
  },
  inputNumber: {
    fontSize: '12px',
    iconSize: '14px',
    handlerIconSize: '10px',
    height: '24px',
    lineHeight: '24px',
    padding: '8px',
  },
  inputSearch: {
    fontSize: '12px',
    iconSize: '12px',
    height: '24px',
    lineHeight: '24px',
    padding: '8px',
  },
  inputText: {
    fontSize: '12px',
    iconSize: '12px',
    height: '24px',
    lineHeight: '24px',
  },
  list: {
    fontSize: '12px',
    titleSize: '14px',
    iconSize: '12px',
    height: '32px',
  },
  menu: {
    titleSize: '14px',
    fontSize: '12px',
    iconSize: '16px',
    titleHeight: '32px',
    itemHeight: '24px',
    iconWidth: '32px',
  },
  modal: {
    fontSize: '12px',
    iconSize: '14px',
    height: '32px',
  },
  pages: {
    fontSize: '12px',
    headerFontSize: '14px',
    imageTitleSize: '28px',
    imageSubtitleSize: '18px',
    siderTitleSize: '18px',
    padding: '8px',
    margin: '8px',
    headerHeight: '32px',
  },
  pagination: {
    fontSize: '12px',
    iconSize: '12px',
    height: '32px',
    width: '32px',
  },
  popover: {
    fontSize: '12px',
    height: '24px',
  },
  progress: {
    fontSize: '12px',
    iconSize: '18px',
    height: '24px',
    width: '24px',
    margin: '4px',
  },
  radioButton: {
    fontSize: '12px',
    wrapperHeight: '24px',
    wrapperLineHeight: '22px',
  },
  radioInput: {
    fontSize: '12px',
    wrapperHeight: '24px',
    wrapperLineHeight: '24px',
  },
  result: {
    titleFontSize: '14px',
    subtitleFontSize: '12px',
    iconSize: '32px',
    margin: '8px',
  },
  scroll: {
    height: '10px',
    width: '10px',
  },
  select: {
    fontSize: '12px',
    height: '24px',
    lineHeight: '24px',
  },
  skeleton: {
    height: '24px',
    width: '24px',
    lineHeight: '24px',
    margin: '8px',
    padding: '8px',
  },
  space: {
    fontSize: '12px',
  },
  spin: {
    fontSize: '12px',
    iconSize: '16px',
  },
  splitPanel: {
    fontSize: '12px',
  },
  steps: {
    barTop: '12px',
    titleSize: '12px',
    descriptionSize: '10px',
    iconSize: '18px',
    height: '24px',
    width: '24px',
    margin: '8px',
    padding: '8px',
  },
  switchButton: {
    fontSize: '12px',
    buttonHeight: '16px',
    buttonLineHeight: '14px',
    handleSize: '10px',
  },
  tabs: {
    barSize: '2px',
    iconSize: '12px',
    fontSize: '12px',
    padding: '8px',
    margin: '8px',
    height: '32px',
    width: '32px',
    lineHeight: '32px',
  },
  text: {
    fontSize: '12px',
  },
  tooltip: {
    fontSize: '12px',
    height: '24px',
    width: '24px',
  },
  transfer: {
    fontSize: '12px',
    iconSize: '12px',
    height: '24px',
    lineHeight: '24px',
  },
  tree: {
    fontSize: '12px',
    iconSize: '12px',
    borderSize: '2px',
    height: '24px',
  },
  underConstruction: {
    fontSize: '12px',
    iconSize: '48px',
    height: '144px',
    width: '144px',
    margin: '8px',
    padding: '8px',
  },
  upload: {
    fontSize: '12px',
    iconSize: '14px',
    height: '48px',
    width: '48px',
    margin: '4px',
  },
  valuePicker: {
    fontSize: '12px',
    iconSize: '14px',
    iconRight: '18px',
    wrapperHeight: '24px',
    wrapperLineHeight: '24px',
    inputHeight: '24px',
    inputLineHeight: '24px',
    padding: '0px 8px',
  },
  widget: {
    fontSize: '12px',
    iconSize: '18px',
    padding: '8px',
    margin: '8px',
  },
  typography: {
    paragraph: {
      fontSize: '12px',
      marginBottom: '8px',
    },
    text: {
      fontSize: '12px',
      marginBottom: '0px',
    },
    title: {
      fontSize: '14px',
      marginBottom: '8px',
    },
  },
};

export default compact;
