import { ThemeLayoutConfig } from '../types';

const cozy: ThemeLayoutConfig = {
  height: {
    lg: '48px',
    md: '40px',
    sm: '32px',
    xs: '24px',
    xss: '16px',
  },
  width: {
    lg: '48px',
    md: '40px',
    sm: '32px',
    xs: '24px',
    xss: '16px',
  },
  margin: {
    lg: '48px',
    md: '32px',
    sm: '16px',
    xs: '8px',
    xss: '4px',
  },
  padding: {
    lg: '48px',
    md: '32px',
    sm: '16px',
    xs: '8px',
    xss: '4px',
  },
  alert: {
    fontSize: '14px',
    iconSize: '24px',
    borderWidth: '1px',
    borderLeftWidth: '3px',
  },
  autoComplete: {
    fontSize: '14px',
    iconSize: '16px',
    wrapperHeight: '32px',
    wrapperLineHeight: '32px',
    inputHeight: '30px',
    inputLineHeight: '30px',
    itemHeight: '24px',
    itemLineHeight: '24px',
  },
  badge: {
    fontSize: '12px',
    height: '24px',
    lineHeight: '24px',
    width: '24px',
  },
  button: {
    fontSize: '14px',
    iconSize: '16px',
    iconButtonWidth: '32px',
    buttonHeight: '32px',
    buttonPadding: '0px 16px',
  },
  card: {
    descriptionSize: '14px',
    iconSize: '48px',
    padding: '16px',
    titleSize: '16px',
  },
  checkbox: {
    fontSize: '14px',
    wrapperHeight: '32px',
    wrapperLineHeight: '32px',
  },
  collapse: {
    fontSize: '14px',
    iconSize: '20px',
    collapseHeight: '40px',
  },
  colorPicker: {
    pickerHeight: '20px',
    pickerWidth: '20px',
    pickerMargin: '6px',
  },
  dataList: {
    fontSize: '14px',
    iconSize: '24px',
    height: '32px',
    lineHeight: '32px',
    width: '32px',
    padding: '16px',
  },
  dataTable: {
    fontSize: '14px',
    iconSize: '16px',
    height: '40px',
    lineHeight: '40px',
    padding: '16px',
    toolbarHeight: '48px',
  },
  divider: {
    fontSize: '14px',
    height: '32px',
  },
  dropDown: {
    fontSize: '14px',
    iconSize: '16px',
    itemHeight: '32px',
    itemLineHeight: '32px',
  },
  empty: {
    fontSize: '16px',
    iconSize: '48px',
    margin: '16px',
  },
  field: {
    height: '32px',
  },
  filter: {
    fontSize: '14px',
  },
  form: {
    fontSize: '14px',
  },
  gridView: {
    fontSize: '14px',
    padding: '16px',
  },
  header: {
    fontSize: '18px',
    iconSize: '20px',
  },
  icon: {
    iconSize: '24px',
  },
  inputNumber: {
    fontSize: '14px',
    iconSize: '18px',
    handlerIconSize: '12px',
    height: '32px',
    lineHeight: '32px',
    padding: '16px',
  },
  inputSearch: {
    fontSize: '14px',
    iconSize: '16px',
    height: '32px',
    lineHeight: '32px',
    padding: '16px',
  },
  inputText: {
    fontSize: '14px',
    iconSize: '16px',
    height: '32px',
    lineHeight: '32px',
  },
  list: {
    fontSize: '14px',
    titleSize: '16px',
    iconSize: '16px',
    height: '48px',
  },
  menu: {
    titleSize: '16px',
    fontSize: '14px',
    iconSize: '20px',
    titleHeight: '48px',
    itemHeight: '32px',
    iconWidth: '48px',
  },
  modal: {
    fontSize: '14px',
    iconSize: '16px',
    height: '48px',
  },
  pages: {
    fontSize: '14px',
    headerFontSize: '16px',
    imageTitleSize: '38px',
    imageSubtitleSize: '24px',
    siderTitleSize: '24px',
    padding: '16px',
    margin: '16px',
    headerHeight: '48px',
  },
  pagination: {
    fontSize: '14px',
    iconSize: '16px',
    height: '40px',
    width: '40px',
  },
  popover: {
    fontSize: '14px',
    height: '32px',
  },
  progress: {
    fontSize: '14px',
    iconSize: '24px',
    height: '32px',
    width: '32px',
    margin: '8px',
  },
  radioButton: {
    fontSize: '14px',
    wrapperHeight: '32px',
    wrapperLineHeight: '30px',
  },
  radioInput: {
    fontSize: '14px',
    wrapperHeight: '32px',
    wrapperLineHeight: '32px',
  },
  result: {
    titleFontSize: '16px',
    subtitleFontSize: '14px',
    iconSize: '64px',
    margin: '16px',
  },
  scroll: {
    height: '12px',
    width: '12px',
  },
  select: {
    fontSize: '14px',
    height: '32px',
    lineHeight: '32px',
  },
  skeleton: {
    height: '32px',
    width: '32px',
    lineHeight: '32px',
    margin: '16px',
    padding: '16px',
  },
  space: {
    fontSize: '14px',
  },
  spin: {
    fontSize: '14px',
    iconSize: '32px',
  },
  splitPanel: {
    fontSize: '14px',
  },
  steps: {
    barTop: '16px',
    titleSize: '14px',
    descriptionSize: '12px',
    iconSize: '14px',
    height: '32px',
    width: '32px',
    margin: '16px',
    padding: '16px',
  },
  switchButton: {
    fontSize: '14px',
    buttonHeight: '24px',
    buttonLineHeight: '22px',
    handleSize: '18px',
  },
  tabs: {
    barSize: '3px',
    iconSize: '16px',
    fontSize: '14px',
    padding: '16px',
    margin: '16px',
    height: '48px',
    width: '48px',
    lineHeight: '48px',
  },
  text: {
    fontSize: '14px',
  },
  tooltip: {
    fontSize: '14px',
    height: '32px',
    width: '32px',
  },
  transfer: {
    fontSize: '14px',
    iconSize: '16px',
    height: '32px',
    lineHeight: '32px',
  },
  tree: {
    fontSize: '14px',
    iconSize: '16px',
    borderSize: '4px',
    height: '32px',
  },
  underConstruction: {
    fontSize: '16px',
    iconSize: '64px',
    height: '192px',
    width: '192px',
    margin: '16px',
    padding: '16px',
  },
  upload: {
    fontSize: '14px',
    iconSize: '24px',
    height: '96px',
    width: '96px',
    margin: '8px',
  },
  valuePicker: {
    fontSize: '14px',
    iconSize: '18px',
    iconRight: '24px',
    wrapperHeight: '32px',
    wrapperLineHeight: '32px',
    inputHeight: '32px',
    inputLineHeight: '32px',
    padding: '0px 16px',
  },
  widget: {
    fontSize: '14px',
    iconSize: '24px',
    padding: '16px',
    margin: '16px',
  },
  typography: {
    paragraph: {
      fontSize: '14px',
      marginBottom: '16px',
    },
    text: {
      fontSize: '14px',
      marginBottom: '0px',
    },
    title: {
      fontSize: '16px',
      marginBottom: '16px',
    },
  },
};

export default cozy;
